language: java
jdk:
  - oraclejdk8
  - openjdk8
dist: trusty
sudo: true
script:
  - gradle wrapper --gradle-version 4.5-rc-1 --distribution-type all && ./gradlew clean build --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
