language: java
sudo: required
dist: trusty
group: edge
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
script:
  - gradle wrapper --gradle-version 4.5-rc-1 --distribution-type all && ./gradlew clean build --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
